### ISSUE TITLE
fiber-navigator crashes when creating two VOIs based on two ROIs

### ISSUE THREAD

**Issue by TBaker76** [scilus/fibernavigator#206] opened 2015-03-26 18:28 UTC
Hi,

I am creating two VOIs based on the subjects ROI (say anterior cingulate, caudate). Both are in diffusion space. When I load the first VOI, no problem, see tracts but i also get this error message (see below). When I load the second ROI, same error message, but fibernavigator crashes. I can load one VOI and then a cube voi and it works. Its seems to have issues only when I load the second ROI. 
Please advise, thanks
Travis 

error message: 

ASSERT INFO:
../src/generic/treectlg.cpp(2248): assert "item.IsOk()" failed in EnsureVisible(): invalid tree item

BACKTRACE:
[1] wxGenericTreeCtrl::EnsureVisible(wxTreeItemId const&)
[2] MainFrame::onSelectTreeItem(wxTreeEvent&)
[3] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
[4] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[5] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[6] wxEvtHandler::TryHereOnly(wxEvent&)
[7] wxEvtHandler::ProcessEventLocally(wxEvent&)
[8] wxEvtHandler::ProcessEvent(wxEvent&)
[9] wxWindowBase::TryAfter(wxEvent&)
[10] wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)
[11] wxGenericTreeCtrl::DoSelectItem(wxTreeItemId const&, bool, bool)
[12] wxGenericTreeCtrl::SelectItem(wxTreeItemId const&, bool)
[13] PropertiesWindow::OnNewVoiFromOverlay(wxCommandEvent&)
[14] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
[15] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[16] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[17] wxEvtHandler::TryHereOnly(wxEvent&)
[18] wxEvtHandler::ProcessEventLocally(wxEvent&)
[19] wxEvtHandler::ProcessEvent(wxEvent&)
[20] wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)
[21] wxWindowBase::TryAfter(wxEvent&)
[22] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[23] g_signal_emit_valist
[24] g_signal_emit
[25] g_closure_invoke
[26] g_signal_emit_valist
[27] g_signal_emit
[28] g_closure_invoke
[29] g_signal_emit_valist
[30] g_signal_emit
[31] gtk_propagate_event
[32] gtk_main_do_event
[33] g_main_context_dispatch
[34] g_main_loop_run
[35] gtk_main
[36] wxGUIEventLoop::DoRun()
[37] wxEventLoopBase::Run()
[38] wxAppConsoleBase::MainLoop()
[39] wxEntry(int&, wchar_t**)
[40] main
[41] __libc_start_main
[42] _start

**Comment by chamberm** [comment] 2015-03-27 12:35
Which platform are you using ? For me, this master (Windows version) works fine when creating and using 2 ROIs for fiber selection -> https://github.com/chamberm/fibernavigator

**Comment by jchoude** [comment] 2015-03-27 13:25
Which branch did you use? It is supposed to be fixed in the rtfmri_coloring_branch.

**Comment by TBaker76** [comment] 2015-03-27 13:57
cmake version: cmake version 2.8.12.2
Ubuntu version: 14.04
compile: rtfmri-coloring-feature branch

**Comment by TBaker76** [comment] 2015-03-27 13:57
cmake version: cmake version 2.8.12.2
Ubuntu version: 14.04
compile: rtfmri-coloring-feature branch

**Comment by chamberm** [comment] 2015-03-27 14:08
Cmake 3... might help ?
else I just tested on Linux Mint 16, 2 ROIs also works with the branch I mentioned earlier.

**Comment by TBaker76** [comment] 2015-03-27 14:24
Thanks, but I am using Ubuntu 14.04. I can successfully compile FN using
cmake 2.8 without any errors.

So what version of FN should I use that this problem is fixed? the github
website is a bit confusing to determine what is the most current version.
Can you send me the link, thanks.

I can create two box ROI/VOIs and it works. But when I use ROIs in the
subjects diffusion space, FN crashes.
Travis

**Comment by chamberm** [comment] 2015-03-27 14:45
Can you maybe describe how you generate your rois ? You load them as mask or you draw them by hand with the drawing tool present in the FN ? What datatype are they

Envoyé de mon iPhone

**Comment by TBaker76** [comment] 2015-03-27 15:03
ROIs are basic, created using WFU_pickatlas, and then registered to the
subjects T1 and diffusion space. I load them as mask, give it some skin,
and then load as VOI for tracking. They are in nii format. Each ROI works
well individually, or when doing tracking between the ROI and a box VOI.
They load fine, and I can load mutliple ROI and FN has no problem. It just
trying to track between the two ROIs.

Is it possible for me to send you an example?
Travis

**Comment by chamberm** [comment] 2015-03-29 16:15
yes absolutly, if you can, send us a link with dropbox files. here is my email: maxime.chamberland@usherbrooke.ca

**Comment by chamberm** [comment] 2015-04-04 14:53
Thx for the data. I will have a look in the next week

**Comment by jchoude** [comment] 2015-04-07 13:45
Hi Travis,

we had a look at your data. The root cause of your problem is that, according to the Fibernavigator, you have negative coordinates in your tracts. If you load them with the T1, and take a look perpendicular to the sagital slice, you will see parts of tracts going down the spinal cord, and going further down than what the anatomy contains.

This is a problem with VOIs, and could take some time to resolve on our part. Personnaly, I cannot put the time to fix this, especially since we are working on a new viewer, which we hope to release freely in the 2, 3 coming weeks.

However, out of curiosity, and to maybe help find a quick way to go around this issue: how were your tracts generated? Using which tools?

Thanks!

**Comment by chamberm** [comment] 2015-04-07 13:51
A simple workaround would be that you ensure that your anatomy containing the ROIs is as large as the tracts, or that you mask out the tracts going this low in the spinal cord (using the T1).

**Comment by TBaker76** [comment] 2015-04-07 14:30
Thanks for looking into this for me. I appreciate your time.Tracts are
computed with a scilpy script: scilpy/scripts/compute_local_tracking_pft.py.

Cheers,
Travis

**Comment by jchoude** [comment] 2015-10-16 13:03
Hi @TBaker76 

pinging back on this. There were delays in the release of the new software. Still, if you encounter this problem again, please send me an email or reopen a new issue, and I'll send you one of 2 potential solutions to your problem.

**Closed by jchoude** 2015-10-16 13:03 UTC
